[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
authors = ["{{authors}}"]
license = "MIT OR Apache-2.0"
description = "GoldSrc plugin written in Rust"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
goldsrc = { git = "https://github.com/goldsrc-rs/goldsrc-rs.git", branch = "dev" }
